M48
; DRILL file {KiCad (7.0.0)} date Sat Apr  1 02:08:27 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-01T02:08:27+13:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.3545Y-3.1744
X4.5455Y-3.1744
T2
X4.3427Y-3.0551
X4.5573Y-3.0551
T0
M30
