M48
; DRILL file {KiCad (7.0.0)} date Mon Mar  6 19:08:15 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-06T19:08:15+13:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0709
%
G90
G05
T1
X2.1313Y-2.7917
X2.1313Y-3.8086
T2
X3.5945Y-2.5744
X3.7855Y-2.5744
T3
X3.5827Y-2.4551
X3.7973Y-2.4551
T0
M30
