import os
import pandas
import pandas as pd

dir_path = os.path.dirname(os.path.realpath(__file__))

# Open CSV files generated by JLCPCB plugin
jlcpcb_bom_filepath = os.path.join(dir_path, 'BOM-pico_expansion_board.csv')

lcsc_bom_headers_with_spaces = 'Quantity,Manufacture Part Number,Manufacturer(optional),Description(optional),LCSC Part Number(optional),Package(optional),Customer Part Number(optional),,'.split(',')
lcsc_bom_headers = [header for header in lcsc_bom_headers_with_spaces if header]

# Read JLCPCB bom file
jlcpcb_bom_df = pd.read_csv(jlcpcb_bom_filepath)
num_rows_before = len(jlcpcb_bom_df)

# Drop rows that doesn't have LCSC
jlcpcb_bom_df = jlcpcb_bom_df.dropna(subset='LCSC')
num_rows_after = len(jlcpcb_bom_df)

print(f"{num_rows_before - num_rows_after} rows removed")

lcsc_bom = []

# Iterate over each row
for idx, row in jlcpcb_bom_df.iterrows():
    lcsc_bom_row = {header: '' for header in lcsc_bom_headers}

    lcsc_bom_row['Quantity'] = len(row['Designator'].split(','))
    lcsc_bom_row['Manufacture Part Number'] = row['Comment']
    lcsc_bom_row['LCSC Part Number(optional)'] = row['LCSC']
    lcsc_bom_row['Description(optional)'] = row['Designator']
    lcsc_bom_row['Package(optional)'] = row['Footprint']

    lcsc_bom.append(lcsc_bom_row)

lcsc_bom_df = pandas.DataFrame(lcsc_bom)
lcsc_bom_df.to_csv(os.path.join(dir_path, 'LCSC_Bom.csv'), index=False)
